title: "Bina Thapa"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default

author:
  name: "Bina Thapa"
  avatar: "/assets/images/BinaThapa_Profile.jpg"
  bio: "Postdoctoral Researcher | Remote Sensing | Forest Ecology"
  location: "Purdue University"

plugins:
  - jekyll-include-cache

# Top navigation tabs
navigation:
  main:
    - title: "Home"
      url: /
    - title: "Research"
      url: /research/
    - title: "Teaching"
      url: /teaching/
    - title: "Google Scholar"
      url: https://scholar.google.com/citations?user=s5t-GKgAAAAJ&hl=en
