title: ""            # leave empty to hide top site title
theme: minimal       # you can choose other themes like 'cayman', 'slate', etc.
description: "Bina Thapa - Postdoctoral researcher at Purdue University"
