title: "Bina Thapa"

#remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: "_pages"
    values:
      layout: default
      permalink: "/:basename/"
