# Site settings
title: "Bina Thapa"
description: "Postdoctoral researcher specializing in remote sensing of forest ecosystems."
baseurl: ""
url: "https://thapabina.github.io"
theme: minimal-mistakes-jekyll
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Bina Thapa"
  avatar: "/assets/images/BinaThapa_Profile.jpg"
  bio: "Postdoctoral researcher specializing in remote sensing of forest ecosystems."
  location: "Purdue University"
  links:
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=s5t-GKgAAAAJ"
    - label: "Research"
      url: "/research/"
    - label: "Teaching"
      url: "/teaching/"
    - label: "Publications"
      url: "/publications/"

nav:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Publications"
    url: "/publications/"

minimal_mistakes_skin: "default"
minimal_mistakes_light_skin: "default"
minimal_mistakes_dark_skin: "dark"

permalink: pretty
safe: true
